FROM node:11.2.0-alpine

WORKDIR /app
COPY . .

RUN npm install -g lerna
RUN lerna bootstrap

FROM node:alpine

WORKDIR /app
# dependencies
COPY --from=0 /app/packages/mocker-shared-lib /mocker-shared-lib/
COPY --from=0 /app/packages/mocker-mock-server /mocker-mock-server/
COPY --from=0 /app/packages/mocker-learning-mode /mocker-learning-mode/
# app
COPY --from=0 /app/packages/mocker-ui .

CMD [ "npm", "start" ]
