FROM node:13.4.0-alpine

WORKDIR /app
COPY . .

RUN npm install -g lerna
RUN lerna bootstrap

FROM node:13.4.0-alpine

WORKDIR /app
COPY --from=0 /app/packages/mocker-shared-lib .

CMD [ "npm", "test" ]
